http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-https-redirectscheme
          - middlewares-secure-headers
          - middlewares-compress

    chain-no-auth-internal:
      chain:
        middlewares:
          - middlewares-internal-only
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-https-redirectscheme
          - middlewares-secure-headers
          - middlewares-compress

    chain-authentik-auth:
      chain:
        middlewares:
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-https-redirectscheme
          - middlewares-secure-headers
          - middlewares-authentik
          - middlewares-compress

    chain-basic-auth:
      chain:
        middlewares:
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-https-redirectscheme
          - middlewares-secure-headers
          - middlewares-basic-auth
          - middlewares-compress