services:
  authentik-db:
    image: postgres:17
    restart: always
    container_name: authentik-db
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $PG_PASS
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${PG_DB:-authentik} -U ${PG_USER:-authentik} "]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

  authentik-redis:
    image: redis:alpine
    restart: always
    container_name: authentik-redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    restart: always
    container_name: authentik-server
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: true
      AUTHENTIK_DISABLE_UPDATE_CHECK: true
      AUTHENTIK_ERROR_REPORTING__ENABLED: false
    volumes:
      - ./media:/media
      - ./templates:/templates
    env_file:
      - .env
    networks:
      - proxy
      - default
    labels:
      traefik.enable: true
      traefik.http.routers.authentik-rtr.entrypoints: https
      traefik.http.routers.authentik-rtr.rule: Host(`$HOST.$DOMAIN`) || HostRegexp(`{subdomain:[A-Za-z0-9](?:[A-Za-z0-9\-]{0,61}[A-Za-z0-9])?}.$DOMAIN`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.authentik-rtr.middlewares: chain-no-auth@file
      traefik.http.routers.authentik-rtr.service: authentik-svc
      traefik.http.services.authentik-svc.loadbalancer.server.port: 9000
    depends_on:
      authentik-db:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    restart: always
    container_name: authentik-worker
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      DOCKER_HOST: tcp://authentik-socket-proxy:2375
    user: root
    volumes:
      - ./media:/media
      - ./certs:/certs
      - ./templates:/templates
    env_file:
      - .env
    depends_on:
      authentik-db:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
      authentik-socket-proxy:
        condition: service_healthy

  authentik-socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: authentik-socket-proxy
    restart: always
    environment:
      TZ: $TZ
      LOG_LEVEL: warning
      POST: 1
      CONTAINERS: 1
      IMAGES: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    read_only: true
    tmpfs:
      - /run
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --no-verbose --tries=1 http://localhost:2375/version > /dev/null 2>&1 || exit 1"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

#  certbot:
#    container_name: authentik-certbot
#    image: certbot/dns-cloudflare:latest
#    volumes:
#      - ./certs/:/etc/letsencrypt
#      - ./cloudflare.ini:/config/cloudflare.ini
#      - ./certbot:/var/log/letsencrypt
#    command: certonly --non-interactive --register-unsafely-without-email --dns-cloudflare --dns-cloudflare-credentials /config/cloudflare.ini --agree-tos -d $HOST.$DOMAIN --server https://acme-v02.api.letsencrypt.org/directory

networks:
  proxy:
    external: true
